# Exercise 1

In [18]:
import numpy as np
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [12]:
random_integers.shape

(20, 5)

In [33]:
r = random_integers[:, 1]
r

array([333008,  42105, 326386,  49982, 231729, 343356, 254634, 406983,
       129585, 335140,   8973,  32213,  56174, 273338, 282399, 101115,
       425024, 180346, 449971,  35455])

# Exercise 2

What is the average value of the second column (to two decimal places)

In [27]:
r = random_integers[:, 1] 
avg = np.mean(r)
avg

214895.8


# Exercise 3
What is the average value of the first 5 rows of the third and fourth columns?

In [35]:
r = random_integers[:5, 2:4]
r

array([[202553, 140037],
       [261540, 481981],
       [110795, 394863],
       [408830, 485118],
       [265455, 109413]])

In [36]:
r = random_integers[:5, 2:4]
avg = np.mean(r)
avg

286058.5

# Exercise 4 

In [37]:
import numpy as np
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(first_matrix)

[[1 2 3]
 [4 5 6]]


In [38]:
second_matrix = np.array([1, 2, 3])
print(second_matrix)

[1 2 3]


In [39]:
first_matrix + second_matrix

array([[2, 4, 6],
       [5, 7, 9]])

# Execise 5

In [40]:
my_vector = np.array([1, 2, 3, 4, 5, 6])
selection = my_vector % 2 == 0
my_vector[selection]

array([2, 4, 6])

# Exercise 7

In [41]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
my_slice = my_array[:, 1:3]
my_slice

array([[2, 3],
       [5, 6]])

# Exercise 8

In [45]:
my_array[:, :] = my_array * 2
my_slice

array([[ 4,  6],
       [10, 12]])

# Exercise 9

In [46]:
my_array = my_array * 2
my_slice

array([[ 4,  6],
       [10, 12]])

# Exercise 10

In [47]:
# precition correct

# Exercise 11

In [48]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
my_slice = my_array[:, 1:3].copy()
my_slice


array([[2, 3],
       [5, 6]])

In [49]:
my_array[:, :] = my_array * 2
my_slice

array([[2, 3],
       [5, 6]])